const items = [
  // ==================== PICOS ====================
  {
    nombre: "🪵 Pico de madera",
    id: "minecraft:wooden_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 2,
    receta: "3 Tablones + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_madera.png"
  },
  {
    nombre: "🪨 Pico de piedra",
    id: "minecraft:stone_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 3,
    receta: "3 Piedra + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_piedra.png"
  },
  {
    nombre: "🟠 Pico de cobre",
    id: "minecraft:copper_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 3,
    receta: "3 Lingotes de cobre + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_cobre.png"
  },
  {
    nombre: "⚙️ Pico de hierro",
    id: "minecraft:iron_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 4,
    receta: "3 Lingotes de hierro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_hierro.png"
  },
  {
    nombre: "🪙 Pico de oro",
    id: "minecraft:golden_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 2,
    receta: "3 Lingotes de oro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_oro.png"
  },
  {
    nombre: "💎 Pico de diamante",
    id: "minecraft:diamond_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 5,
    receta: "3 Diamantes + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pico_diamante.png"
  },
  {
    nombre: "🪨 Pico de netherita",
    id: "minecraft:netherite_pickaxe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 6,
    receta: "1 Pico de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/pico_netherita.png"
  },

  // ==================== PALAS ====================
  {
    nombre: "🥄 Pala de madera",
    id: "minecraft:wooden_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 2.5,
    receta: "1 Tablón + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_madera.png"
  },
  {
    nombre: "🥄 Pala de piedra",
    id: "minecraft:stone_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 3.5,
    receta: "1 Piedra + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_piedra.png"
  },
  {
    nombre: "🟠 Pala de cobre",
    id: "minecraft:copper_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 3.5,
    receta: "1 Lingote de cobre + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_cobre.png"
  },
  {
    nombre: "⚙️ Pala de hierro",
    id: "minecraft:iron_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 4.5,
    receta: "1 Lingote de hierro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_hierro.png"
  },
  {
    nombre: "🪙 Pala de oro",
    id: "minecraft:golden_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 2.5,
    receta: "1 Lingote de oro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_oro.png"
  },
  {
    nombre: "💎 Pala de diamante",
    id: "minecraft:diamond_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 5.5,
    receta: "1 Diamante + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pala_diamante.png"
  },
  {
    nombre: "🥄 Pala de netherita",
    id: "minecraft:netherite_shovel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 6.5,
    receta: "1 Pala de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/pala_netherita.png"
  },

  // ==================== ESPADAS ====================
  {
    nombre: "🗡️ Espada de madera",
    id: "minecraft:wooden_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 4,
    receta: "2 Tablones + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_madera.png"
  },
  {
    nombre: "🗡️ Espada de piedra",
    id: "minecraft:stone_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 5,
    receta: "2 Piedra + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_piedra.png"
  },
  {
    nombre: "🗡️ Espada de cobre",
    id: "minecraft:copper_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 5,
    receta: "2 Lingotes de cobre + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_cobre.png"
  },
  {
    nombre: "🗡️ Espada de hierro",
    id: "minecraft:iron_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 6,
    receta: "2 Lingotes de hierro + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_hierro.png"
  },
  {
    nombre: "🗡️ Espada de oro",
    id: "minecraft:golden_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 4,
    receta: "2 Lingotes de oro + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_oro.png"
  },
  {
    nombre: "🗡️ Espada de diamante",
    id: "minecraft:diamond_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 7,
    receta: "2 Diamantes + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/espada_diamante.png"
  },
  {
    nombre: "🗡️ Espada de netherita",
    id: "minecraft:netherite_sword",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 8,
    receta: "1 Espada de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/espada_netherita.png"
  },

  // ==================== HACHAS ====================
  {
    nombre: "🪓 Hacha de madera",
    id: "minecraft:wooden_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 7,
    receta: "3 Tablones + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_madera.png"
  },
  {
    nombre: "🪓 Hacha de piedra",
    id: "minecraft:stone_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 9,
    receta: "3 Piedra + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_piedra.png"
  },
  {
    nombre: "🟠 Hacha de cobre",
    id: "minecraft:copper_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 9,
    receta: "3 Lingotes de cobre + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_cobre.png"
  },
  {
    nombre: "⚙️ Hacha de hierro",
    id: "minecraft:iron_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 9,
    receta: "3 Lingotes de hierro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_hierro.png"
  },
  {
    nombre: "🪙 Hacha de oro",
    id: "minecraft:golden_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 7,
    receta: "3 Lingotes de oro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_oro.png"
  },
  {
    nombre: "💎 Hacha de diamante",
    id: "minecraft:diamond_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 9,
    receta: "3 Diamantes + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hacha_diamante.png"
  },
  {
    nombre: "🪓 Hacha de netherita",
    id: "minecraft:netherite_axe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 10,
    receta: "1 Hacha de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/hacha_netherita.png"
  },

  // ==================== AZADAS ====================
  {
    nombre: "🌾 Azada de madera",
    id: "minecraft:wooden_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 1,
    receta: "2 Tablones + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_madera.png"
  },
  {
    nombre: "🌾 Azada de piedra",
    id: "minecraft:stone_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 1,
    receta: "2 Piedra + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_piedra.png"
  },
  {
    nombre: "🌾 Azada de cobre",
    id: "minecraft:copper_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 1,
    receta: "2 Lingotes de cobre + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_cobre.png"
  },
  {
    nombre: "🌾 Azada de hierro",
    id: "minecraft:iron_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 1,
    receta: "2 Lingotes de hierro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_hierro.png"
  },
  {
    nombre: "🌾 Azada de oro",
    id: "minecraft:golden_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 1,
    receta: "2 Lingotes de oro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_oro.png"
  },
  {
    nombre: "🌾 Azada de diamante",
    id: "minecraft:diamond_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 1,
    receta: "2 Diamantes + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azada_diamante.png"
  },
  {
    nombre: "🌾 Azada de netherita",
    id: "minecraft:netherite_hoe",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 1,
    receta: "1 Azada de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/azada_netherita.png"
  },

  // ==================== LANZAS ====================
  {
    nombre: "🔱 Lanza de madera",
    id: "minecraft:wooden_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 59,
    daño: 1,
    receta: "1 Tablón + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_madera.png"
  },
  {
    nombre: "🔱 Lanza de piedra",
    id: "minecraft:stone_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 131,
    daño: 2,
    receta: "1 Piedra + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_piedra.png"
  },
  {
    nombre: "🔱 Lanza de cobre",
    id: "minecraft:copper_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 190,
    daño: 1,
    receta: "1 Lingote de Cobre + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_cobre.png"
  },
  {
    nombre: "🔱 Lanza de hierro",
    id: "minecraft:iron_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 250,
    daño: 3,
    receta: "1 Lingote de hierro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_hierro.png"
  },
  {
    nombre: "🔱 Lanza de oro",
    id: "minecraft:golden_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 32,
    daño: 1,
    receta: "1 Lingote de oro + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_oro.png"
  },
  {
    nombre: "🔱 Lanza de diamante",
    id: "minecraft:diamond_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 1561,
    daño: 4,
    receta: "1 Diamante + 2 Palos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/lanza_diamante.png"
  },
  {
    nombre: "🔱 Lanza de netherita",
    id: "minecraft:netherite_spear",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 2031,
    daño: 5,
    receta: "1 Lanza de diamante + 1 Lingote de netherita + 1 Plantilla",
    mesa: "Mesa de herrería",
    img: "assets/craft/lanza_netherita.png"
  },

  // ==================== POCIONES ====================
  {
    nombre: "Receta de las Pociones",
    id: "",
    categoria: "Equipo",
    stack: "",
    durabilidad: "",
    daño: "",
    receta: "",
    mesa: "",
    img: "assets/craft/recetas.png"
  },
  {
    nombre: "🧪 Poción de Regeneración",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Lágrima de Ghast + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_regeneracion.png"
  },
  {
    nombre: "🧪 Poción de Rapidez",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Azúcar + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_rapidez.png"
  },
  {
    nombre: "🧪 Poción de Resistencia al Fuego",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Crema de Magma + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_resistencia_fuego.png"
  },
  {
    nombre: "🧪 Poción de Curación",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Sandía Reluciente + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_curacion.png"
  },
  {
    nombre: "🧪 Poción de Visión Nocturna",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Zanahoria Dorada + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_vision_nocturna.png"
  },
  {
    nombre: "🧪 Poción de Fuerza",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Polvo de Blaze + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_fuerza.png"
  },
  {
    nombre: "🧪 Poción de Salto",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Pata de Conejo + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_salto.png"
  },
  {
    nombre: "🧪 Poción de Respiración Acuática",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Pez Globo + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_respiracion.png"
  },
  {
    nombre: "🧪 Poción de Invisibilidad",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Ojo de Araña Fermentado + Poción de Visión Nocturna",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_invisibilidad.png"
  },
  {
    nombre: "🧪 Poción de Caída Lenta",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Membrana de Fantasma + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_caida_lenta.png"
  },
  {
    nombre: "🧪 Poción del Maestro Tortuga",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Caparazón de Tortuga + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_tortuga.png"
  },
  {
    nombre: "🧪 Poción de Veneno",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Ojo de Araña + Poción Rara",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_veneno.png"
  },
  {
    nombre: "🧪 Poción de Debilidad",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Ojo de Araña Fermentado + Frasco de Agua",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_debilidad.png"
  },
  {
    nombre: "🧪 Poción de Lentitud",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Ojo de Araña Fermentado + Poción de Rapidez",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_lentitud.png"
  },
  {
    nombre: "🧪 Poción de Daño",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Ojo de Araña Fermentado + Poción de Curación",
    mesa: "Soporte de pociones",
    img: "assets/craft/pocion_dano.png"
  },

  // ==================== BRÚJULAS Y MAPAS ====================
  {
    nombre: "🧭 Brújula",
    id: "minecraft:compass",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "4 Lingotes de hierro + 1 Redstone",
    mesa: "Mesa de crafteo",
    img: "assets/craft/brujula.png"
  },
  {
    nombre: "🧭 Brújula de Recuperación",
    id: "minecraft:recovery_compass",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "8 Fragmentos de Eco + 1 Brújula",
    mesa: "Mesa de crafteo",
    img: "assets/craft/brujula_recuperacion.png"
  },
  {
    nombre: "🗺️ Mapa Vacío",
    id: "minecraft:map",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "8 Papel + 1 Brújula",
    mesa: "Mesa de crafteo",
    img: "assets/craft/mapa_vacio.png"
  },
  {
    nombre: "🗺️ Mapa Localizador",
    id: "minecraft:filled_map",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Mapa Vacío + Brújula",
    mesa: "Mesa de crafteo",
    img: "assets/craft/mapa_localizador.png"
  },
  {
    nombre: "⏰ Reloj",
    id: "minecraft:clock",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "4 Lingotes de oro + 1 Redstone",
    mesa: "Mesa de crafteo",
    img: "assets/craft/reloj.png"
  },

  // ==================== MECHEROS Y UTILIDADES ====================
  {
    nombre: "🔥 Mechero",
    id: "minecraft:flint_and_steel",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 64,
    daño: 0,
    receta: "1 Lingote de hierro + 1 Pedernal",
    mesa: "Mesa de crafteo",
    img: "assets/craft/mechero.png"
  },
  {
    nombre: "✂️ Tijeras",
    id: "minecraft:shears",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 238,
    daño: 0,
    receta: "2 Lingotes de hierro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tijeras.png"
  },
  {
    nombre: "🪣 Cubo",
    id: "minecraft:bucket",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Lingotes de hierro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/cubo.png"
  },
  {
    nombre: "🎣 Caña de Pescar",
    id: "minecraft:fishing_rod",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 64,
    daño: 0,
    receta: "3 Palos + 2 Hilos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/cana_pescar.png"
  },
  {
    nombre: "🪢 Rienda",
    id: "minecraft:lead",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "4 Hilos + 1 Bola de Slime",
    mesa: "Mesa de crafteo",
    img: "assets/craft/rienda1.png,assets/craft/rienda2.png"
  },
  {
    nombre: "🪶 Élitros",
    id: "minecraft:elytra",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 432,
    daño: 0,
    receta: "No se fabrica. Se encuentra en las ciudades del End",
    mesa: "Ninguna",
    img: "assets/craft/elytra.png"
  },

  // ==================== ALIMENTOS ====================
  {
    nombre: "🍎 Manzana",
    id: "minecraft:apple",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene de hojas de roble y roble oscuro",
    mesa: "Ninguna",
    img: "assets/craft/manzana.png"
  },
  {
    nombre: "🥕 Zanahoria",
    id: "minecraft:carrot",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene de cultivos",
    mesa: "Ninguna",
    img: "assets/craft/zanahoria.png"
  },
  {
    nombre: "🥔 Patata",
    id: "minecraft:potato",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene de cultivos",
    mesa: "Ninguna",
    img: "assets/craft/patata.png"
  },
  {
    nombre: "🍞 Pan",
    id: "minecraft:bread",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "3 Trigos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pan.png"
  },
  {
    nombre: "🥩 Filete Cocido",
    id: "minecraft:cooked_beef",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Carne Cruda",
    mesa: "Horno",
    img: "assets/craft/filete_cocido.png"
  },
  {
    nombre: "🍗 Pollo Cocido",
    id: "minecraft:cooked_chicken",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Pollo Crudo",
    mesa: "Horno",
    img: "assets/craft/pollo_cocido.png"
  },
  {
    nombre: "🍖 Cerdo Cocido",
    id: "minecraft:cooked_porkchop",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Chuleta de Cerdo Cruda",
    mesa: "Horno",
    img: "assets/craft/cerdo_cocido.png"
  },
  {
    nombre: "🐟 Salmón Cocido",
    id: "minecraft:cooked_salmon",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Salmón Crudo",
    mesa: "Horno",
    img: "assets/craft/salmon_cocido.png"
  },
  {
    nombre: "🐟 Bacalao Cocido",
    id: "minecraft:cooked_cod",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Bacalao Crudo",
    mesa: "Horno",
    img: "assets/craft/bacalao_cocido.png"
  },
  {
    nombre: "🍖 Cordero Cocido",
    id: "minecraft:cooked_mutton",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Cordero Crudo",
    mesa: "Horno",
    img: "assets/craft/cordero_cocido.png"
  },
  {
    nombre: "🌿 Alga Marina Seca",
    id: "minecraft:dried_kelp",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Alga Marina",
    mesa: "Horno",
    img: "assets/craft/alga_seca.png"
  },

  // ==================== BOLAS DE NIEVE Y CAPARAZÓN ====================
  {
    nombre: "❄️ Bola de Nieve",
    id: "minecraft:snowball",
    categoria: "Equipo",
    stack: 16,
    durabilidad: 0,
    daño: 0,
    receta: "4 Bolas de Nieve (de nieve)",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bola_nieve.png"
  },
  {
    nombre: "🐢 Caparazón de Tortuga",
    id: "minecraft:turtle_helmet",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 275,
    daño: 0,
    receta: "5 Escamas de Tortuga",
    mesa: "Mesa de crafteo",
    img: "assets/craft/caparazon_tortuga.png"
  },

  // ==================== BOTELLAS ====================
  {
    nombre: "🍾 Botella Vacía",
    id: "minecraft:glass_bottle",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "3 Vidrio",
    mesa: "Mesa de crafteo",
    img: "assets/craft/botella_vacia.png"
  },
  {
    nombre: "✨ Botella de Experiencia",
    id: "minecraft:experience_bottle",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "No se fabrica. Se obtiene de comerciar con clérigos o de cofres",
    mesa: "Ninguna",
    img: "assets/craft/botella_experiencia.png"
  },

  // ==================== NATURALEZA ====================
  {
    nombre: "🌿 Alfombra de Musgo",
    id: "minecraft:moss_carpet",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Bloque de Musgo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/alfombra_musgo.png"
  },
  {
    nombre: "🪨 Andesita",
    id: "minecraft:andesite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Diorita + 1 Piedra",
    mesa: "Mesa de crafteo",
    img: "assets/craft/andesita.png"
  },
  {
    nombre: "🪨 Andesita Pulida",
    id: "minecraft:polished_andesite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Andesita",
    mesa: "Mesa de crafteo",
    img: "assets/craft/andesita_pulida.png"
  },
  {
    nombre: "💜 Bloque de Amatista",
    id: "minecraft:amethyst_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Fragmentos de Amatista",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_amatista.png"
  },
  {
    nombre: "🟫 Arcilla",
    id: "minecraft:clay",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene excavando bloques de arcilla",
    mesa: "Ninguna",
    img: "assets/craft/arcilla.png"
  },
  {
    nombre: "🎋 Bloque de Bambú",
    id: "minecraft:bamboo_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Bambú",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_bambu.png"
  },
  {
    nombre: "🪨 Bloque de Dripstone",
    id: "minecraft:dripstone_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Dripstone puntiagudas",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_dripstone.png"
  },
  {
    nombre: "🌋 Bloque de Magma",
    id: "minecraft:magma_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Crema de Magma",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_magma.png"
  },
  {
    nombre: "❄️ Bloque de Nieve",
    id: "minecraft:snow_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Bolas de Nieve",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_nieve.png"
  },
  {
    nombre: "🔴 Bloque de Verrugas del Nether",
    id: "minecraft:nether_wart_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Verrugas del Nether",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_verrugas_nether.png"
  },
  {
    nombre: "⬛ Basalto Pulido",
    id: "minecraft:polished_basalt",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Basaltos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/basalto_pulido.png"
  },
  {
    nombre: "🎃 Calabaza Iluminada",
    id: "minecraft:jack_o_lantern",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Calabaza tallada + 1 Antorcha",
    mesa: "Mesa de crafteo",
    img: "assets/craft/calabaza_iluminada.png"
  },
  {
    nombre: "🫀 Corazón de Creaking",
    id: "minecraft:creaking_heart",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Bloques de Resina + Troncos de Roble Pálido",
    mesa: "Mesa de crafteo",
    img: "assets/craft/corazon_creaking.png"
  },
  {
    nombre: "🪨 Diorita",
    id: "minecraft:diorite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Cuarzo del Nether + 1 Piedra",
    mesa: "Mesa de crafteo",
    img: "assets/craft/diorita.png"
  },
  {
    nombre: "🪨 Diorita Pulida",
    id: "minecraft:polished_diorite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Dioritas",
    mesa: "Mesa de crafteo",
    img: "assets/craft/diorita_pulida.png"
  },
  {
    nombre: "🟠 Grumo de Resina",
    id: "minecraft:resin_clump",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene del Corazón de Creaking",
    mesa: "Ninguna",
    img: "assets/craft/grumo_resina.png"
  },
  {
    nombre: "🪨 Granito",
    id: "minecraft:granite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Diorita + 1 Cuarzo del Nether",
    mesa: "Mesa de crafteo",
    img: "assets/craft/granito.png"
  },
  {
    nombre: "🪨 Granito Pulido",
    id: "minecraft:polished_granite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Granitos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/granito_pulido.png"
  },
  {
    nombre: "🧊 Hielo Azul",
    id: "minecraft:blue_ice",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Hielos Compactados",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hielo_azul.png"
  },
  {
    nombre: "🧊 Hielo Compactado",
    id: "minecraft:packed_ice",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Hielos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/hielo_compactado.png"
  },
  {
    nombre: "🪨 Deepslate Pulida",
    id: "minecraft:polished_deepslate",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Pizarras Profundas",
    mesa: "Mesa de crafteo",
    img: "assets/craft/deepslate_pulida.png"
  },
  {
    nombre: "⬛ Piedra Negra Pulida",
    id: "minecraft:polished_blackstone",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Piedras Negras",
    mesa: "Mesa de crafteo",
    img: "assets/craft/piedra_negra_pulida.png"
  },
  {
    nombre: "🟫 Tierra Gruesa",
    id: "minecraft:coarse_dirt",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "2 Tierra + 2 Grava",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tierra_gruesa.png"
  },
  {
    nombre: "🪨 Toba Pulida",
    id: "minecraft:polished_tuff",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Toba",
    mesa: "Mesa de crafteo",
    img: "assets/craft/toba_pulida.png"
  },
  {
    nombre: "🌱 Semillas de Trigo",
    id: "minecraft:wheat_seeds",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtienen rompiendo hierba",
    mesa: "Ninguna",
    img: "assets/craft/semillas_trigo.png"
  },
  {
    nombre: "🍉 Bloque de Sandía",
    id: "minecraft:melon",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Rodajas de Sandía",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_sandia.png"
  },
  {
    nombre: "📡 Sensor de Sculk Calibrado",
    id: "minecraft:calibrated_sculk_sensor",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Sensor de Sculk + 3 Fragmentos de Amatista",
    mesa: "Mesa de crafteo",
    img: "assets/craft/sculk_calibrado.png"
  },
  {
    nombre: "🦴 Polvo de Hueso",
    id: "minecraft:bone_meal",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Hueso → 3 Polvos de Hueso",
    mesa: "Mesa de crafteo",
    img: "assets/craft/polvo_hueso1.png,assets/craft/polvo_hueso2.png"
  },

  // ==================== MADERAS ====================
  {
    nombre: "🪵 Madera de Roble",
    id: "minecraft:oak_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Roble",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_roble.png"
  },
  {
    nombre: "🪵 Madera de Abedul",
    id: "minecraft:birch_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Abedul",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_abedul.png"
  },
  {
    nombre: "🪵 Madera de Abeto",
    id: "minecraft:spruce_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Abeto",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_abeto.png"
  },
  {
    nombre: "🪵 Madera de Jungla",
    id: "minecraft:jungle_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Jungla",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_jungla.png"
  },
  {
    nombre: "🪵 Madera de Acacia",
    id: "minecraft:acacia_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Acacia",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_acacia.png"
  },
  {
    nombre: "🪵 Madera de Roble Oscuro",
    id: "minecraft:dark_oak_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Roble Oscuro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_roble_oscuro.png"
  },
  {
    nombre: "🪵 Madera de Manglar",
    id: "minecraft:mangrove_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Manglar",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_manglar.png"
  },
  {
    nombre: "🪵 Madera de Cerezo",
    id: "minecraft:cherry_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Cerezo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_cerezo.png"
  },
  {
    nombre: "🪵 Madera de Bambú",
    id: "minecraft:bamboo_mosaic",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "2 Losas de Bambú",
    mesa: "Mesa de crafteo",
    img: "assets/craft/mosaico_bambu.png"
  },
  {
    nombre: "🪵 Madera de Crimson",
    id: "minecraft:crimson_hyphae",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Tallos de Crimson",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_crimson.png"
  },
  {
    nombre: "🪵 Madera de Warped",
    id: "minecraft:warped_hyphae",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Tallos de Warped",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_warped.png"
  },
  {
    nombre: "🪵 Madera de Roble Pálido",
    id: "minecraft:pale_oak_wood",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Troncos de Roble Pálido",
    mesa: "Mesa de crafteo",
    img: "assets/craft/madera_roble_palido.png"
  },

  // ==================== EQUIPO ====================
  {
    nombre: "🛡️ Armadura de Lobo",
    id: "minecraft:wolf_armor",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 64,
    daño: 0,
    receta: "6 Escamas de Armadillo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/armadura_lobo.png"
  },
  {
    nombre: "🔨 Maza",
    id: "minecraft:mace",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 500,
    daño: 5,
    receta: "1 Núcleo Pesado + 1 Vara de Breeze",
    mesa: "Mesa de crafteo",
    img: "assets/craft/maza.png"
  },
  {
    nombre: "🖌️ Brocha",
    id: "minecraft:brush",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 64,
    daño: 0,
    receta: "1 Pluma + 1 Lingote de Cobre + 1 Palo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/brocha.png"
  },
  {
    nombre: "🔭 Catalejo",
    id: "minecraft:spyglass",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Fragmento de Amatista + 2 Lingotes de Cobre",
    mesa: "Mesa de crafteo",
    img: "assets/craft/catalejo.png"
  },
  {
    nombre: "💨 Carga de Viento",
    id: "minecraft:wind_charge",
    categoria: "Equipo",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Vara de Breeze → 4 Cargas de Viento",
    mesa: "Mesa de crafteo",
    img: "assets/craft/carga_viento.png"
  },
  {
    nombre: "🎒 Saco",
    id: "minecraft:bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Cuero + 1 Hilo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco.png"
  },

  // ==================== ARNESES ====================
  {
    nombre: "🤍 Arnes Blanco / Montura para Ghast Blanco",
    id: "minecraft:white_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Blanca",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_blanco.png"
  },
  {
    nombre: "🧡 Arnes Naranja / Montura para Ghast Naranja",
    id: "minecraft:orange_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Naranja",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_naranja.png"
  },
  {
    nombre: "💗 Arnes Magenta / Montura para Ghast Magenta",
    id: "minecraft:magenta_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Magenta",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_magenta.png"
  },
  {
    nombre: "💙 Arnes Azul Claro / Montura para Ghast Azul Claro",
    id: "minecraft:light_blue_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Azul Claro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_azul_claro.png"
  },
  {
    nombre: "💛 Arnes Amarillo / Montura para Ghast Amarillo",
    id: "minecraft:yellow_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Amarilla",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_amarillo.png"
  },
  {
    nombre: "💚 Arnes Lima / Montura para Ghast Lima",
    id: "minecraft:lime_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Lima",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_lima.png"
  },
  {
    nombre: "💗 Arnes Rosa / Montura para Ghast Rosa",
    id: "minecraft:pink_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Rosa",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_rosa.png"
  },
  {
    nombre: "🩶 Arnes Gris / Montura para Ghast Gris",
    id: "minecraft:gray_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Gris",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_gris.png"
  },
  {
    nombre: "⬜ Arnes Gris Claro / Montura para Ghast Gris Claro",
    id: "minecraft:light_gray_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Gris Claro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_gris_claro.png"
  },
  {
    nombre: "🩵 Arnes Cian / Montura para Ghast Cian",
    id: "minecraft:cyan_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Cian",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_cian.png"
  },
  {
    nombre: "💜 Arnes Púrpura / Montura para Ghast Púrpura",
    id: "minecraft:purple_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Púrpura",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_purpura.png"
  },
  {
    nombre: "💙 Arnes Azul / Montura para Ghast Azul",
    id: "minecraft:blue_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Azul",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_azul.png"
  },
  {
    nombre: "🤎 Arnes Marrón / Montura para Ghast Marrón",
    id: "minecraft:brown_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Marrón",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_marron.png"
  },
  {
    nombre: "💚 Arnes Verde / Montura para Ghast Verde",
    id: "minecraft:green_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Verde",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_verde.png"
  },
  {
    nombre: "❤️ Arnes Rojo / Montura para Ghast Rojo",
    id: "minecraft:red_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Roja",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_rojo.png"
  },
  {
    nombre: "🖤 Arnes Negro / Montura para Ghast Negro",
    id: "minecraft:black_harness",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "3 Cuero + 2 Vidrio + 1 Lana Negra",
    mesa: "Mesa de crafteo",
    img: "assets/craft/arnes_negro.png"
  },
    // ==================== SACOS DE COLORES ====================

  {
    nombre: "🎒 Saco Blanco",
    id: "minecraft:white_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Blanco",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_blanco.png"
  },
  {
    nombre: "🎒 Saco Naranja",
    id: "minecraft:orange_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Naranja",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_naranja.png"
  },
  {
    nombre: "🎒 Saco Magenta",
    id: "minecraft:magenta_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Magenta",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_magenta.png"
  },
  {
    nombre: "🎒 Saco Azul Claro",
    id: "minecraft:light_blue_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Azul Claro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_azul_claro.png"
  },
  {
    nombre: "🎒 Saco Amarillo",
    id: "minecraft:yellow_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Amarillo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_amarillo.png"
  },
  {
    nombre: "🎒 Saco Lima",
    id: "minecraft:lime_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Lima",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_lima.png"
  },
  {
    nombre: "🎒 Saco Rosa",
    id: "minecraft:pink_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Rosa",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_rosa.png"
  },
  {
    nombre: "🎒 Saco Gris",
    id: "minecraft:gray_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Gris",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_gris.png"
  },
  {
    nombre: "🎒 Saco Gris Claro",
    id: "minecraft:light_gray_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Gris Claro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_gris_claro.png"
  },
  {
    nombre: "🎒 Saco Cian",
    id: "minecraft:cyan_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Cian",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_cian.png"
  },
  {
    nombre: "🎒 Saco Púrpura",
    id: "minecraft:purple_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Púrpura",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_purpura.png"
  },
  {
    nombre: "🎒 Saco Azul",
    id: "minecraft:blue_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Azul",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_azul.png"
  },
  {
    nombre: "🎒 Saco Marrón",
    id: "minecraft:brown_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Marrón",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_marron.png"
  },
  {
    nombre: "🎒 Saco Verde",
    id: "minecraft:green_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Verde",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_verde.png"
  },
  {
    nombre: "🎒 Saco Rojo",
    id: "minecraft:red_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Rojo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_rojo.png"
  },
  {
    nombre: "🎒 Saco Negro",
    id: "minecraft:black_bundle",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "1 Saco + 1 Tinte Negro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/saco_negro.png"
  },

  // ==================== TINTES ====================

  {
    nombre: "🎨 Tinte Blanco",
    id: "minecraft:white_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Harina de Hueso",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_blanco.png"
  },
  {
    nombre: "🎨 Tinte Amarillo",
    id: "minecraft:yellow_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Diente de León o 1 Girasol",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_amarillo.png"
  },
  {
    nombre: "🎨 Tinte Azul",
    id: "minecraft:blue_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Lapislázuli o 1 Aciano",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_azul.png"
  },
  {
    nombre: "🎨 Tinte Azul Claro",
    id: "minecraft:light_blue_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Orquídea Azul",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_azul_claro.png"
  },
  {
    nombre: "🎨 Tinte Cian",
    id: "minecraft:cyan_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Azul + 1 Tinte Verde",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_cian.png"
  },
  {
    nombre: "🎨 Tinte Gris",
    id: "minecraft:gray_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Negro + 1 Tinte Blanco",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_gris.png"
  },
  {
    nombre: "🎨 Tinte Gris Claro",
    id: "minecraft:light_gray_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Blanco + 1 Tinte Negro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_gris_claro.png"
  },
  {
    nombre: "🎨 Tinte Lima",
    id: "minecraft:lime_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Verde + 1 Tinte Blanco",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_lima.png"
  },
  {
    nombre: "🎨 Tinte Magenta",
    id: "minecraft:magenta_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Púrpura + 1 Tinte Rosa",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_magenta.png"
  },
  {
    nombre: "🎨 Tinte Marrón",
    id: "minecraft:brown_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Cacao",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_marron.png"
  },
  {
    nombre: "🎨 Tinte Naranja",
    id: "minecraft:orange_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Rojo + 1 Tinte Amarillo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_naranja.png"
  },
  {
    nombre: "🎨 Tinte Púrpura",
    id: "minecraft:purple_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tinte Rojo + 1 Tinte Azul",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_purpura.png"
  },
  {
    nombre: "🎨 Tinte Rojo",
    id: "minecraft:red_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Amapola o 1 Tulipán Rojo",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_rojo.png"
  },
  {
    nombre: "🎨 Tinte Rosa",
    id: "minecraft:pink_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Tulipán Rosa o 1 Peonía",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tinte_rosa.png"
  },
  {
    nombre: "🎨 Tinte Verde",
    id: "minecraft:green_dye",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Cactus",
    mesa: "Horno",
    img: "assets/craft/tinte_verde.png"
  },

  // ==================== OTROS OBJETOS DE LAS IMÁGENES ====================

  {
    nombre: "🍾 Botella de Agua",
    id: "minecraft:potion",
    categoria: "Equipo",
    stack: 1,
    durabilidad: 0,
    daño: 0,
    receta: "Botella Vacía + Agua",
    mesa: "Ninguna",
    img: "assets/craft/botella.png"
  },
  {
    nombre: "🍬 Azúcar",
    id: "minecraft:sugar",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Caña de Azúcar",
    mesa: "Mesa de crafteo",
    img: "assets/craft/azucar.png"
  },
  {
    nombre: "💙 Lapislázuli",
    id: "minecraft:lapis_lazuli",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "x1 Bloque de lapislázuli",
    mesa: "Mesa de Crafteo",
    img: "assets/craft/lapis.png"
  },
  {
    nombre: "🍉 Sandia",
    id: "minecraft:melon",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "x1 Bloque de Sandia",
    mesa: "Mesa de Crafteo",
    img: "assets/craft/bloque_sandia.png"
  },
  {
    nombre: "🥕 Zanahoria Dorada",
    id: "minecraft:golden_carrot",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Zanahoria + 8 Pepitas de Oro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/zanahoria_dorada.png"
  },
  {
    nombre: "🍉 Sandía Dorada",
    id: "minecraft:glistering_melon_slice",
    categoria: "Objetos",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Rodaja de Sandía + 8 Pepitas de Oro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/sandia_dorada.png"
  },
  {
    nombre: "🌾 Trigo",
    id: "minecraft:wheat",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene de cultivos de trigo",
    mesa: "Ninguna",
    img: "assets/craft/trigo.png"
  },
  {
    nombre: "🎃 Semillas de Calabaza",
    id: "minecraft:pumpkin_seeds",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Calabaza",
    mesa: "Mesa de crafteo",
    img: "assets/craft/semilla_calabaza.png"
  },
  {
    nombre: "🍉 Semillas de Sandía",
    id: "minecraft:melon_seeds",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "1 Rodaja de Sandía",
    mesa: "Mesa de crafteo",
    img: "assets/craft/semilla_sandia.png"
  },
  {
    nombre: "🟫 Tierra Basta",
    id: "minecraft:coarse_dirt",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "2 Tierra + 2 Grava",
    mesa: "Mesa de crafteo",
    img: "assets/craft/tierra_basta.png"
  },
  {
    nombre: "🪨 Pizarra Abismal Pulida",
    id: "minecraft:polished_deepslate",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Pizarra Abismal",
    mesa: "Mesa de crafteo",
    img: "assets/craft/pizarra_abismal_pulida.png"
  },
  {
    nombre: "⬛ Rocanegra Pulida",
    id: "minecraft:polished_blackstone",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Rocanegra",
    mesa: "Mesa de crafteo",
    img: "assets/craft/rocanegra_pulida.png"
  },
  {
    nombre: "🟫 Raíces de Manglar Lodosas",
    id: "minecraft:muddy_mangrove_roots",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Raíces de Manglar + Barro",
    mesa: "Mesa de crafteo",
    img: "assets/craft/raices_manglar_lodosa.png"
  },
  {
    nombre: "🟣 Fragmento de Resina",
    id: "minecraft:resin_clump",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Se obtiene del Corazón de Creaking",
    mesa: "Ninguna",
    img: "assets/craft/fragmento_resina.png"
  },
  {
    nombre: "🧱 Bloque de Arcilla",
    id: "minecraft:clay",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Bolas de Arcilla",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_arcilla.png"
  },
  {
    nombre: "🪨 Bloque de Espeleotema",
    id: "minecraft:dripstone_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Espeleotemas Puntiagudos",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_espeleoctema.png"
  },
  {
    nombre: "🔴 Bloque de Verrugas",
    id: "minecraft:nether_wart_block",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "9 Verrugas del Nether",
    mesa: "Mesa de crafteo",
    img: "assets/craft/bloque_verruga.png"
  },
  {
    nombre: "🌱 Alfombra de Musgo Pálido",
    id: "minecraft:pale_moss_carpet",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "Bloque de Musgo Pálido",
    mesa: "Mesa de crafteo",
    img: "assets/craft/alfombra_musgo_palido.png"
  },
  {
    nombre: "🪨 Andesita Pulida",
    id: "minecraft:polished_andesite",
    categoria: "Naturaleza",
    stack: 64,
    durabilidad: 0,
    daño: 0,
    receta: "4 Andesita",
    mesa: "Mesa de crafteo",
    img: "assets/craft/ansesita_pulida.png"
    }
];

module.exports = items;
